export const QUESTIONNAIRE_CLEAR = 'QUESTIONNAIRE_CLEAR';
export const QUESTIONNAIRE_SETUP = 'QUESTIONNAIRE_SETUP';
export const RULE_EVALUATION = 'RULE_EVALUATION';

export const RESPONSE_CHOICE_ADD = 'RESPONSE_CHOICE_ADD';
export const RESPONSE_CHOICE_REMOVE = 'RESPONSE_CHOICE_REMOVE';
export const RESPONSE_CHOICE_SET = 'RESPONSE_CHOICE_SET';
export const RESPONSE_CHOICE_CLEAR = 'RESPONSE_CHOICE_CLEAR';

export const RESPONSE_INPUT_SET = 'RESPONSE_INPUT_SET';
export const RESPONSE_INPUT_CLEAR = 'RESPONSE_INPUT_CLEAR';

export const PAGE_NAVIGATION = 'PAGE_NAVIGATION';






